import {
  ArrowRight,
  Baby,
  BadgeCheck,
  CalendarCheck,
  Check,
  ChevronDown,
  Clock,
  FileText,
  Flower2,
  Globe,
  Heart,
  HeartHandshake,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  Plane,
  Quote,
  Scale,
  Send,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Users,
  X,
} from "lucide-react";

/**
 * Maps the icon names used in `src/config/content.js` to icon components.
 * Kept in a plain module (it exports no components) so React Fast Refresh
 * keeps working.
 */
export const iconMap = {
  heart: Heart,
  flower: Flower2,
  sparkle: Sparkles,
  shield: ShieldCheck,
  stethoscope: Stethoscope,
  scale: Scale,
  users: Users,
  lock: Lock,
  globe: Globe,
  baby: Baby,
  badge: BadgeCheck,
  calendar: CalendarCheck,
  plane: Plane,
  handshake: HeartHandshake,
  document: FileText,
  quote: Quote,
  check: Check,
  arrow: ArrowRight,
  chevron: ChevronDown,
  menu: Menu,
  close: X,
  star: Star,
  phone: Phone,
  mail: Mail,
  pin: MapPin,
  clock: Clock,
  chat: MessageCircle,
  send: Send,
};
